
[[toc5_00]]
== Discussions
In Japan's urban digital twin project "PLATEAU," the development, utilization, and open data of 3D city models are being promoted. The project adopts CityGML 2.0, an international standard, for its 3D city models and creates a comprehensive product specification by repeatedly reflecting the needs derived from use cases developed in various cities into the ADE (Application Domain Extension). At the same time, the project enables the creation of profiles tailored to the use cases of each city, providing a mechanism to address city-specific needs. Furthermore, PLATEAU aims to build an ecosystem that allows various stakeholders from the public and private sectors, as well as academia, to autonomously promote the development, utilization, and open data of 3D city models. Since its launch in 2020, PLATEAU has developed 3D city models for over 250 cities and created more than 100 use cases within five years. The concepts of "Standardization and Localization" and "Ecosystem Building” underpin the rapid development.

* **Standardization and Localization**
** The standardization of 3D city models not only enhances data reusability but also improves productivity and quality management efficiency, allowing for a focused allocation of resources to non-standardized areas. The ADE mechanism of CityGML enables the localization of standards. By rapidly repeating the cycle of examination and implementation through this "localization," social implementation can be accelerated while continuously updating the standards. This approach allows the standards to evolve as "living standards" in response to changes in applicable technologies and societal conditions. 
** The gap that exists between standards and actual practices places a burden on the operation and sustainability of those standards. To mitigate this gap, effectively applying the standards to maximize the use of existing processes and data, along with "localization" of the standards, proves to be effective.

* **Ecosystem Building**
** The sustainability of 3D city models is a crucial key in the implementation of UDTs. It is necessary to build an ecosystem that clarifies who the main stakeholders are and what roles each should play, and to operate this ecosystem effectively. This ecosystem must reflect the realities of each country and city.
** In Japan, municipalities are continuously and comprehensively developing geospatial data based on legal regulations. However, in the context of societal changes such as declining birth rates and an aging population, the number of municipalities capable of newly developing 3D city models is limited. While temporary investments might be possible, sustaining them over the long term poses challenges in most cases. Therefore, PLATEAU is promoting the development of tools and support systems that enable continuous development and updating of 3D city models without burdening municipalities by positioning the geospatial data they develop as a resource. Additionally, efforts are underway to develop tools for utilizing 3D city models. By implementing foundational policies and environmental improvements, the national government is supporting and accelerating the autonomous development, utilization, and open data of 3D city models by various stakeholders in the ecosystem.
** The foundational and environmental policies supporting this ecosystem include not only the initiatives led by the MLIT overseeing PLATEAU, but also the efforts of related ministries, such as the establishment of standards through JPGIS and the creation of the Geospatial Information Center to promote open data. The incorporation of insights gained from these past initiatives into the project is also a core reason behind its significant advancements.

In the future, the expansion of PLATEAU's initiatives domestically is expected, along with the sharing of insights gained from these activities with various countries and cities, contributing to the sustainable implementation of UDTs. To achieve this, the following efforts are necessary: 

* **Promotion of ADE**
** At PLATEAU, active development of Urban Planning ADE focuses on localizing standards to address the challenges and needs of diverse municipalities across Japan using 3D city models. Due to the diverse structures of ADEs, there are no universally applicable software solutions, and PLATEAU has engaged in individual development efforts. PLATEAU shares the results of these efforts as open source and documentation. 
** These assets are utilized when expanding to other cities in Japan that face similar challenges and needs. However, common use cases exist in various countries and cities around the world. The assets developed by PLATEAU can also be leveraged by countries and cities working on similar use case developments. They can achieve further advancements and efficiencies by using these assets, and if the results are fed back into the system, the use cases in Japanese cities can also be enhanced and streamlined.
** However, at present, there is no system for broadly sharing ADEs and related technologies. There are portal sites such as https://github.com/OloOcki/awesome-citygml[“Awesome CityGML”] and https://www.citygmlwiki.org/index.php?title=Citygml_Wiki[“CityGML Wiki”], but their operation is uncertain. A platform that aggregates knowledge and resources related to ADE development from various countries and cities enables the reuse of these resources in next-generation development, and facilitate the spread of the standard.
** This platform will serve as a collection of ideas to enhance future versions of CityGML. For example, PLATEAU has extended the Urban Planning ADE to allow for the subdivision of LOD and to explicitly present this as a quality attribute for each city object to data users. Various stakeholders provide data to create and update 3D city models. In such cases, understanding the quality of each city object becomes especially important, and this may be the starting point for considering metadata in CityGML.
** It is recommended for OGC and the related Working Groups to take the lead on these matters.

* **Support for Transitioning to CityGML 3.0**
** With the introduction of new modules, such as integration with point clouds and dynamic data, as well as indoor LOD representations and a significantly extended transportation module that allows for the representation of detailed street space models with lane-level accuracy, CityGML 3.0 has expanded the possibilities for utilizing 3D city models across a broader range of use cases. Additionally, CityGML 3.0 aims for compatibility with other standards, including IFC. Taking these advantages into consideration, PLATEAU is exploring a transition to CityGML 3.0.
** However, PLATEAU has already accumulated various assets, including 3D city models compliant with CityGML 2.0 and tools that utilize them. The motivation to transition to CityGML 3.0 is low for use cases that municipalities and private companies can realize with CityGML 2.0. Furthermore, PLATEAU will also need to revise the Urban Planning ADE to ensure compatibility with CityGML 3.0, which may pose technical challenges in significantly altering the product specifications of 3D city models and potentially compromise the operation of the ecosystem.
** Therefore, PLATEAU is considering measures to reduce the burden on data creators and users. For example, the development of an upgrade converter from CityGML 2.0 to CityGML 3.0 and a downgrade converter from CityGML 3.0 to CityGML 2.0 are potential strategies.

In the future, various countries and cities will introduce CityGML 3.0, transitioning from CityGML 2.0. These initiatives may occur simultaneously around the world, and the existence of a platform to share the knowledge accumulated from these efforts would enable collaborative solutions to each other's challenges. As a result, feedback from these outcomes could further enhance the quality of the standards.

An open community that openly shares insights on effectively applying the open standard CityGML and collaboratively addressing challenges in its adoption would significantly accelerate the dissemination of CityGML and foster positive developments in its implementation. This applies not only to CityGML but also to other standards. The OGC systematically develops various standards to enable seamless information exchange across different systems. However, users of the standards may encounter challenges in applying them because they do not know which standards to combine or how to differentiate between them. Therefore, there is a need for the open community to continually promote the use of standards.
