
[[toc6_00]]
== Conclusions
In Japan’s urban digital twin realization project "PLATEAU," stakeholders are actively promoting the development, utilization, and open data sharing of 3D city models. The underpinning principles of PLATEAU include "openness," "flat collaboration," and "sustainability." By centering on the international standard CityGML and localizing the international standard according to specific use cases, and by making the resulting technologies and knowledge openly available, PLATEAU aims to broaden the base of participants. This approach enables various stakeholders from industry, government, and academia to utilize 3D city models and create new value by combining their respective strengths and weaknesses. Each entity enhances sustainability by autonomously promoting the development, utilization, and open data sharing of 3D city models.

Furthermore, this initiative extends beyond Japan; through CityGML, the project enables collaboration with various countries that adopt this standard. However, since PLATEAU primarily documents its resources in Japanese, overcoming the language barrier is essential for achieving effective collaboration with international partners. To facilitate the global utilization of PLATEAU's insights, translating the materials into multiple languages, including English and other widely used languages, is important. 

Moving forward, PLATEAU's mission will also include contributing to the realization of UDTs in each country and city. This will be achieved through the dissemination of open-source software (OSS) and know-how derived from the developed Urban Planning ADE and various use cases that implement the ADE, as well as insights related to the application of the StandardsOps methodology. Additionally, the existence of an open community as a platform for sharing the knowledge and experiences gained through these standards is important.
